version: "3.3"
services:
  app:
    build:
      context: .
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/nestestate_frontend
    ports:
      - '3000:3000'
    image: app:react
    container_name: react_container
    command: npm start